name: Neovim checkhealth
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
    - master
  push:
    branches:
      - master

jobs:
  checkhealth:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        neovim:
          - version: v0.10.0
            health_checks: "vim.lsp vim.treesitter"
          - version: stable
            health_checks: "vim.deprecated vim.lsp vim.provider vim.treesitter"
          - version: nightly
            health_checks: "vim.deprecated vim.lsp vim.provider vim.treesitter"

    runs-on: ${{ matrix.os }}
    name: "OS: ${{ matrix.os }} - Neovim: ${{ matrix.neovim.version }}"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.neovim.version }}

      - name: Run :checkhealth
        uses: ColinKennedy/nvim-checkhealth-gh-action@v1.1.1
        with:
          executable: 'nvim -u "spec/minimal_init.lua"'
          # Skip vim.health because it validates the CI runner's terminal, and
          # Neovim nightly treats its missing graphics protocol as an error.
          checks: ${{ matrix.neovim.health_checks }}
