name: Lint

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
    - master
  push:
    branches:
      - master

jobs:
  stylua:
    name: StyLua
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install StyLua
      uses: JohnnyMorganz/stylua-action@v4.1.0
      with:
        version: latest
        token: ${{ secrets.GITHUB_TOKEN }}
        args: false

    - name: Lint
      run: |
        make check-stylua

  luacheck:
    name: Luacheck
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Luacheck
      run: |
        sudo apt-get update
        sudo apt-get install -y luarocks
        sudo luarocks install luacheck

    - name: Lint
      run: |
        make luacheck

  privata:
    name: privata
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install A Lua Interpreter
      uses: leafo/gh-actions-lua@v11
      with:
        luaVersion: "luajit-openresty"

    - name: Install LuaRocks
      # TODO: Replace with https://github.com/luarocks/gh-actions-luarocks after v6+
      uses: ColinKennedy/gh-actions-luarocks@v1.0.0

    - name: Install privata
      run: |
        luarocks install privata

    - name: Lint
      run: |
        make privata

  deadcode:
    name: deadcode
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install A Lua Interpreter
      uses: leafo/gh-actions-lua@v11
      with:
        luaVersion: "luajit-openresty"

    - name: Install LuaRocks
      # TODO: Replace with https://github.com/luarocks/gh-actions-luarocks after v6+
      uses: ColinKennedy/gh-actions-luarocks@v1.0.0

    - name: Install deadcode
      run: |
        luarocks install deadcode

    - name: Lint
      run: |
        make deadcode

  typer:
    name: typer
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Neovim
      uses: rhysd/action-setup-vim@v1
      # NOTE: We need Neovim installed in order to expose the $VIMRUNTIME
      # environment variable
      with:
        neovim: true
        version: stable

    - name: Install A Lua Interpreter
      uses: leafo/gh-actions-lua@v11
      with:
        luaVersion: "luajit-openresty"

    - name: Install LuaRocks
      # TODO: Replace with https://github.com/luarocks/gh-actions-luarocks after v6+
      uses: ColinKennedy/gh-actions-luarocks@v1.0.0

    - name: Install typer
      run: |
        luarocks install typer

    - name: Lint
      run: |
        # We use SSH in the `Makefile` but GitHub Actions cannot authenticate
        # those clones. Rewrite GitHub SSH URLs to HTTPS in CI only.
        export GIT_CONFIG=~/.gitconfig
        git config url."https://github.com/".insteadOf git@github.com:

        make typer

  llscheck:
    name: llscheck
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Neovim
      uses: rhysd/action-setup-vim@v1
      # NOTE: We need Neovim installed in order to expose the $VIMRUNTIME
      # environment variable
      with:
        neovim: true
        version: stable

    - name: Install A Lua Interpreter
      uses: leafo/gh-actions-lua@v11
      with:
        # Neovim is compiled with LuaJIT so we might as well match. But it
        # doesn't look like we can match it exactly.
        #
        # Reference:
        #    https://github.com/leafo/gh-actions-lua/issues/49#issuecomment-2295071198
        #
        luaVersion: "luajit-openresty"

    - name: Install lua-language-server
      uses: jdx/mise-action@v2
      with:
        tool_versions: |
          lua-language-server latest

    - name: Install LuaRocks
      # TODO: Replace with https://github.com/luarocks/gh-actions-luarocks after v6+
      uses: ColinKennedy/gh-actions-luarocks@v1.0.0

    - name: Install llscheck
      run: |
        luarocks install llscheck

    - name: Print Version
      run: |
        lua-language-server --version

    - name: Lint
      run: |
        # We use SSH in the `Makefile` but GitHub actions don't allow that. So
        # we force git to clone using HTTP instead.
        #
        export GIT_CONFIG=~/.gitconfig
        git config url."https://github.com/".insteadOf git@github.com:

        # Now do the llscheck (and any git clones, as needed)
        make llscheck CONFIGURATION=.github/workflows/.luarc.json
