name: StyLua

on:
  pull_request:
    branches:
    - master
  push:
    branches:
      - master

jobs:
  stylua:
    name: StyLua
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install StyLua
        uses: JohnnyMorganz/stylua-action@v4.1.0
        with:
          version: latest
          token: ${{ secrets.GITHUB_TOKEN }}
          args: false

      - name: Run StyLua
        run: |
          make check-stylua
