name: Test

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
    - master
  push:
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        neovim: [v0.11.0, stable, nightly]
        luaVersion: ["luajit-openresty"]
        include:
        - os: "windows-latest"
          toolchain: "msvc"
          luaVersion: "5.1"
          neovim: "v0.11.0"
        - os: "windows-latest"
          toolchain: "msvc"
          luaVersion: "5.1"
          neovim: "stable"
        - os: "windows-latest"
          toolchain: "msvc"
          luaVersion: "5.1"
          neovim: "nightly"

    runs-on: ${{ matrix.os }}
    name: "OS: ${{ matrix.os }} - Neovim: ${{ matrix.neovim }} - Lua: ${{ matrix.luaVersion }}"

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Install Neovim
      uses: rhysd/action-setup-vim@v1
      with:
        neovim: true
        version: ${{ matrix.neovim }}

    - name: Setup MSVC
      # the 'luarocks/gh-actions-lua' step requires msvc to build PUC-Rio Lua
      # versions on Windows (LuaJIT will be build using MinGW/gcc).
      if: ${{ matrix.toolchain == 'msvc' }}
      uses: ilammy/msvc-dev-cmd@v1

    - name: Install Lua
      uses: luarocks/gh-actions-lua@master
      with:
        luaVersion: "${{ matrix.luaVersion }}"

    - name: Install LuaRocks
      uses: ColinKennedy/gh-actions-luarocks@v1.0.0

    - name: Print LuaRocks Version
      run: |
        luarocks --version

    - name: Install Test Dependencies
      run: |
        luarocks install busted

    - name: Test
      run: |
        make test
